#! /bin/sh

bspc rule -r "*"
xset r rate 220 40

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
#if [ -x $HOME/.config/bin/dual_monitor.sh ];then
#	    $HOME/.config/bin/dual_monitor.sh
#fi
#xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --right-of DisplayPort-0 --mode 1280x800 --rotate right
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --right-of DisplayPort-0 --mode 1280x800 --rotate normal
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6
bspc monitor HDMI-A-0 -d 7 8

setxkbmap es
xset r rate 220 40


sxhkd &
#feh --bg-scale --no-fehbg /home/franc/background/wwoman.png &
picom --config /home/franc/.config/compton/compton.conf &
wmname LG3D &
~/.config/polybar/launch.sh &
nm-applet &
dunst &

bspc config pointer_modifier mod1
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Caja desktop='^6' state=floating follow=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Thunderbird desktop='^2'
#bspc rule -a firefox desktop='^3'
#bspc rule -a TelegramDesktop desktop='^4'
#bspc rule -a Jami-gnome desktop='^5'
bspc rule -a Zathura state=tiled
#bspc rule -a mate-terninal desktop='^1' state=maximized

#mate-terminal &



